question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from the moon.", "answer": "False"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Cats have five toes on their front paws.", "answer": "False"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "The Eiffel Tower can grow taller in the summer due to the expansion of iron.", "answer": "True"},
    {"text": "Owls can turn their heads 360 degrees.", "answer": "False"},
    {"text": "A group of crows is called a 'murder'.", "answer": "True"},
    {"text": "The longest time a person has ever lived is 150 years.", "answer": "False"},
    {"text": "Penguins are only found in the Antarctic.", "answer": "False"},
    {"text": "Spiders have six legs.", "answer": "False"},
    {"text": "The sun is a planet.", "answer": "False"},
    {"text": "The fastest land animal is the cheetah.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "A sneeze travels at over 100 miles per hour.", "answer": "False"},
    {"text": "The shortest war in history was between Britain and Zanzibar in 1896.", "answer": "True"},
    {"text": "The moon is made of green cheese.", "answer": "False"},
    {"text": "Astronauts grow taller in space.", "answer": "True"}
]
